[workspace]
members = [
    "styks-blocky-parser",
    "styks-cli",
    "styks-contracts",
    "styks-core",
    "styks-make-parser",
]
resolver = "2"

[workspace.dependencies]
odra = "2.7.2"
odra-test = "2.7.2"
odra-build = "2.7.2"
odra-cli = "2.7.2"
odra-modules = "2.7.2"

[profile.release]
codegen-units = 1
lto = true

[profile.dev.package."*"]
opt-level = 3
